
import type { GroundTruthData } from './types';
import { Sentiment } from './types';

export const GROUND_TRUTH_DATA: GroundTruthData[] = [
    // Positive
    { text: "The service was absolutely fantastic, I couldn't be happier!", sentiment: Sentiment.Positive },
    { text: "This is the best product I have ever purchased. Highly recommended.", sentiment: Sentiment.Positive },
    { text: "I had a wonderful experience. The staff was incredibly helpful.", sentiment: Sentiment.Positive },
    { text: "An amazing film with a brilliant cast. A must-see!", sentiment: Sentiment.Positive },
    { text: "The quality exceeded my expectations. I am thoroughly impressed.", sentiment: Sentiment.Positive },
    { text: "What a delightful surprise! The food was exquisite.", sentiment: Sentiment.Positive },
    { text: "I love the new design. It's so sleek and modern.", sentiment: Sentiment.Positive },
    { text: "Customer support was quick to respond and resolved my issue perfectly.", sentiment: Sentiment.Positive },
    { text: "A truly outstanding performance. I was captivated from start to finish.", sentiment: Sentiment.Positive },
    { text: "The trip was a dream come true. Everything was perfectly organized.", sentiment: Sentiment.Positive },
    { text: "This app is a game-changer. It has simplified my workflow immensely.", sentiment: Sentiment.Positive },
    { text: "I'm so grateful for their help. They went above and beyond.", sentiment: Sentiment.Positive },
    { text: "The concert was electrifying! An unforgettable night.", sentiment: Sentiment.Positive },
    { text: "Beautiful scenery and a very relaxing atmosphere.", sentiment: Sentiment.Positive },
    { text: "The results are incredible. I've seen a huge improvement.", sentiment: Sentiment.Positive },
    { text: "This book is a masterpiece. I couldn't put it down.", sentiment: Sentiment.Positive },
    { text: "They offer great value for money. I will definitely be a repeat customer.", sentiment: Sentiment.Positive },
    { text: "The user interface is intuitive and easy to navigate.", sentiment: Sentiment.Positive },
    { text: "A spectacular event with flawless execution.", sentiment: Sentiment.Positive },
    { text: "The community is so welcoming and friendly. I feel right at home.", sentiment: Sentiment.Positive },

    // Negative
    { text: "I am extremely disappointed with the quality of this item.", sentiment: Sentiment.Negative },
    { text: "The customer service was terrible; they were rude and unhelpful.", sentiment: Sentiment.Negative },
    { text: "This product broke after just one use. A complete waste of money.", sentiment: Sentiment.Negative },
    { text: "The movie was boring and the plot was predictable.", sentiment: Sentiment.Negative },
    { text: "My order arrived late and was damaged. I am very upset.", sentiment: Sentiment.Negative },
    { text: "The software is full of bugs and crashes constantly.", sentiment: Sentiment.Negative },
    { text: "I had a horrible experience at that restaurant. The food was cold.", sentiment: Sentiment.Negative },
    { text: "The instructions were confusing and impossible to follow.", sentiment: Sentiment.Negative },
    { text: "I would not recommend this service to anyone. It was a disaster.", sentiment: Sentiment.Negative },
    { text: "The hotel room was dirty and did not match the pictures online.", sentiment: Sentiment.Negative },
    { text: "This update has made the app unusable. I regret installing it.", sentiment: Sentiment.Negative },
    { text: "I was overcharged for the service and they refused to issue a refund.", sentiment: Sentiment.Negative },
    { text: "The performance was lackluster and uninspired.", sentiment: Sentiment.Negative },
    { text: "The company's policies are unfair and anti-consumer.", sentiment: Sentiment.Negative },
    { text: "I've been on hold for over an hour. This is unacceptable.", sentiment: Sentiment.Negative },
    { text: "The material feels cheap and flimsy. It won't last long.", sentiment: Sentiment.Negative },
    { text: "A terrible decision that will have long-term negative consequences.", sentiment: Sentiment.Negative },
    { text: "The website is slow and difficult to navigate.", sentiment: Sentiment.Negative },
    { text: "I am frustrated by the lack of communication and support.", sentiment: Sentiment.Negative },
    { text: "The whole process was a complete nightmare from start to finish.", sentiment: Sentiment.Negative },

    // Neutral
    { text: "The package was delivered today at 3 PM.", sentiment: Sentiment.Neutral },
    { text: "This report contains the financial data for the last quarter.", sentiment: Sentiment.Neutral },
    { text: "The car is blue and has four doors.", sentiment: Sentiment.Neutral },
    { text: "The meeting is scheduled for tomorrow morning.", sentiment: Sentiment.Neutral },
    { text: "The product is made of plastic and metal.", sentiment: Sentiment.Neutral },
    { text: "The system will be down for maintenance tonight.", sentiment: Sentiment.Neutral },
    { text: "He is the new manager of the sales department.", sentiment: Sentiment.Neutral },
    { text: "The library is located on the third floor.", sentiment: Sentiment.Neutral },
    { text: "The device requires two AA batteries to operate.", sentiment: Sentiment.Neutral },
    { text: "The document is available for download in PDF format.", sentiment: Sentiment.Neutral },
    { text: "The temperature outside is 20 degrees Celsius.", sentiment: Sentiment.Neutral },
    { text: "The train is expected to arrive on time.", sentiment: Sentiment.Neutral },
    { text: "This is a statement of fact.", sentiment: Sentiment.Neutral },
    { text: "The office will be closed on Monday for the public holiday.", sentiment: Sentiment.Neutral },
    { text: "To complete the setup, please follow the on-screen instructions.", sentiment: Sentiment.Neutral },
    { text: "The user manual provides detailed information about the features.", sentiment: Sentiment.Neutral },
    { text: "The event will take place at the convention center.", sentiment: Sentiment.Neutral },
    { text: "The flight number is BA2490.", sentiment: Sentiment.Neutral },
    { text: "Please refer to section 4 of the contract for more details.", sentiment: Sentiment.Neutral },
    { text: "The item's dimensions are 10cm by 5cm by 2cm.", sentiment: Sentiment.Neutral },
];
